name: india_air_quality_json

# Controls when the workflow will run
on:
  schedule:
    - cron: '45 * * * *'  # Runs every 45th minute

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies and upgrade pip
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "snowflake-snowpark-python[pandas]"
          
      # List files and check the current directory
      - name: Check current directory and list files
        run: |
          ls -la
          pwd

      # Run the Python script
      - name: Run ingest-api-data.py script
        run: |
          home_dir=$(pwd)
          echo $home_dir
          python $home_dir/ingest-api-data.py
